const express = require('express');
const cors= require('cors');
const app = express();
require('./config/mongoose.config');
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(cors());
const port = 8000;
require('./routes/product.routes')(app);  
app.listen(port, () => console.log(`Listening on port: ${port}`) );
